 import { Shield, RefreshCw, MessageCircle, Zap, Heart, Globe } from "lucide-react";
 
 const reasons = [
   {
     icon: Shield,
     title: "100% Free Service",
     description: "All our creative services are completely free. No hidden charges, no premium tiers—just quality work delivered to you.",
   },
   {
     icon: Heart,
     title: "Human-Crafted Quality",
     description: "Every piece of content is created by a real person who understands nuance, context, and your specific needs—not generated by AI.",
   },
   {
     icon: RefreshCw,
     title: "Unlimited Revisions",
     description: "Not quite right? Request corrections as many times as needed until you're completely satisfied with the result.",
   },
   {
     icon: MessageCircle,
     title: "Direct Communication",
     description: "Work directly with the creator. Ask questions, provide feedback, and get updates throughout the process.",
   },
   {
     icon: Zap,
     title: "Quick Turnaround",
     description: "Most projects are completed within hours to a few days, depending on complexity. You'll know the timeline upfront.",
   },
   {
     icon: Globe,
     title: "Bilingual Support",
     description: "Content available in both English and Tamil, ensuring your message reaches your audience in their preferred language.",
   },
 ];
 
 const WhyChooseUsSection = () => {
   return (
     <section className="py-20 md:py-28 bg-secondary/30">
       <div className="container mx-auto px-4">
         {/* Section Header */}
         <div className="text-center max-w-2xl mx-auto mb-16">
           <span className="inline-block px-4 py-1 rounded-full bg-card text-sm font-medium text-foreground mb-4">
             Why Choose Us
           </span>
           <h2 className="font-serif text-3xl md:text-4xl lg:text-5xl font-bold text-foreground mb-4">
             The Human Difference in a{" "}
             <span className="text-gradient-forest">Digital World</span>
           </h2>
           <p className="text-muted-foreground text-lg">
             While AI can generate content quickly, it can't understand your vision the way a human can. 
             We deliver exactly what you need—no compromises.
           </p>
         </div>
 
         {/* Reasons Grid */}
         <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
           {reasons.map((reason, index) => (
             <div
               key={reason.title}
               className="p-6 rounded-xl bg-card border border-border hover:border-primary/20 transition-all duration-300 group"
               style={{ animationDelay: `${index * 0.1}s` }}
             >
               <div className="w-12 h-12 rounded-lg bg-secondary flex items-center justify-center mb-4 group-hover:bg-primary group-hover:scale-110 transition-all duration-300">
                 <reason.icon className="w-6 h-6 text-primary group-hover:text-primary-foreground transition-colors" />
               </div>
               <h3 className="font-serif text-lg font-bold text-foreground mb-2">
                 {reason.title}
               </h3>
               <p className="text-muted-foreground text-sm leading-relaxed">
                 {reason.description}
               </p>
             </div>
           ))}
         </div>
       </div>
     </section>
   );
 };
 
 export default WhyChooseUsSection;